on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2
            any::dplyr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run R script
        run: Rscript -e 'source("main.R")'

      - name: Commit results
        run: |
          git config --local user.email "kyalosevens@gmail.com"
          git config --local user.name "franciskyalo"
          git add plots
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"